import { DDCShelf, DDCShelfCatalog } from "@/types/shelf";

export const INITIAL_DDC_SHELVES: DDCShelf[] = [
  {
    shelfID: "Shelf_DDC_000_ComputerScience",
    shelfCode: "SHELF 004–006",
    categoryTitle: "Computer Science & Programming",
    targetCollege: "College of Engineering and Computer Studies",
    iconType: "Journal",
    generalCollectionSummary: "Programming, software, database at computer networks.",
    studentGuidance: "Stack 000.01–320.99. Call number C 004–006.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_100_Philosophy",
    shelfCode: "SHELF 100–199",
    categoryTitle: "Philosophy & Psychology",
    targetCollege: "General Education / CAS",
    iconType: "Journal",
    generalCollectionSummary: "Pilosopiya, sikolohiya, ethics, at lohika.",
    studentGuidance: "Ground floor general stacks 100–199.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_200_Religion",
    shelfCode: "SHELF 200–299",
    categoryTitle: "Religion & Mythology",
    targetCollege: "General Education / CAS",
    iconType: "Journal",
    generalCollectionSummary: "Relihiyon, mitolohiya, theology, at world faiths.",
    studentGuidance: "Ground floor general stacks 200–299.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_300_SocialSciences",
    shelfCode: "SHELF 300–399",
    categoryTitle: "Social Sciences & Education",
    targetCollege: "College of Education and Social Sciences",
    iconType: "Journal",
    generalCollectionSummary: "Batas, sosyolohiya, edukasyon, ekonomiya at lipunan.",
    studentGuidance: "Stack 000.01–320.99 at 321.00–424.99. Call number C 300–399.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_400_Language",
    shelfCode: "SHELF 400–499",
    categoryTitle: "Language & Linguistics",
    targetCollege: "College of Arts and Sciences",
    iconType: "Journal",
    generalCollectionSummary: "Grammar, linggwistika, diksyunaryo, at wikang banyaga.",
    studentGuidance: "Ground floor general stacks 400–499.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_500_PureSciences",
    shelfCode: "SHELF 500–599",
    categoryTitle: "Pure Sciences & Mathematics",
    targetCollege: "College of Arts and Sciences",
    iconType: "Journal",
    generalCollectionSummary: "Math, chemistry, physics, biology, at ecology.",
    studentGuidance: "Stack 425.00–550.00 at 550.01–612.00. Call number C 500–599.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_600_Agriculture",
    shelfCode: "SHELF 630–639",
    categoryTitle: "Agriculture & Animal Science",
    targetCollege: "College of Agriculture Systems & Technology",
    iconType: "Journal",
    generalCollectionSummary: "Pananim at palay, lupa, peste, forestry at paghahayupan.",
    studentGuidance: "Stack 612.01–634.69, nagpapatuloy sa 634.70–658.09. Call number C 630–639.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_600_Technology",
    shelfCode: "SHELF 600–629",
    categoryTitle: "Technology & Applied Sciences",
    targetCollege: "College of Engineering and Computer Studies",
    iconType: "Journal",
    generalCollectionSummary: "Engineering, applied sciences, manufacturing at teknolohiya.",
    studentGuidance: "Ground floor general stacks 600–629.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_636_AnimalHusbandry",
    shelfCode: "SHELF 636",
    categoryTitle: "Animal Husbandry & Livestock",
    targetCollege: "College of Veterinary Medicine & Agriculture",
    iconType: "Journal",
    generalCollectionSummary: "Pagaalaga ng hayop, poultry, swine, at pasture management.",
    studentGuidance: "West wall stacks 636.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_637_Veterinary",
    shelfCode: "SHELF 637–658",
    categoryTitle: "Veterinary & Dairy Science",
    targetCollege: "College of Veterinary Medicine",
    iconType: "Journal",
    generalCollectionSummary: "Veterinary medicine, dairy processing, at animal health.",
    studentGuidance: "West wall stacks 637–658.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_658_Management",
    shelfCode: "SHELF 658",
    categoryTitle: "Management & Commerce",
    targetCollege: "College of Business Studies",
    iconType: "Journal",
    generalCollectionSummary: "Business management, accounting, marketing, at entrepreneurship.",
    studentGuidance: "West wall stacks 658.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_660_ChemicalEngg",
    shelfCode: "SHELF 660–699",
    categoryTitle: "Chemical Engineering",
    targetCollege: "College of Engineering",
    iconType: "Journal",
    generalCollectionSummary: "Chemical technology, manufacturing, at food processing.",
    studentGuidance: "West wall stacks 660–699.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_700_Arts",
    shelfCode: "SHELF 700–799",
    categoryTitle: "Arts & Recreation",
    targetCollege: "College of Arts and Sciences",
    iconType: "Journal",
    generalCollectionSummary: "Musika, sining, arkitektura, sports, at recreation.",
    studentGuidance: "Ground floor general stacks 700–799.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_800_Literature",
    shelfCode: "SHELF 800–899",
    categoryTitle: "Literature",
    targetCollege: "General Education / All Colleges",
    iconType: "Journal",
    generalCollectionSummary: "Tula, dula, sanaysay, rhetoric at literary criticism.",
    studentGuidance: "Mga bookcase sa pader: 700.00–807.99, 808.00–808.819 at 808.82–939.99.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_900_History",
    shelfCode: "SHELF 900–999",
    categoryTitle: "History & Geography",
    targetCollege: "General Education / All Colleges",
    iconType: "Journal",
    generalCollectionSummary: "Kasaysayan ng daigdig, heograpiya, talambuhay, at mapa.",
    studentGuidance: "Ground floor general stacks 900–999.",
    floor: "ground",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Shelf_DDC_FIL_Filipiniana",
    shelfCode: "FILIPINIANA (FIL)",
    categoryTitle: "Filipiniana Collection",
    targetCollege: "All Students & Researchers",
    iconType: "Journal",
    generalCollectionSummary: "Mga aklat tungkol sa Pilipinas o isinulat ng mga Pilipino, kasama ang Pampanga.",
    studentGuidance: "Filipiniana Section, Second Floor. Ang call number ay nagsisimula sa FIL.",
    floor: "second",
    zone: "filipiniana",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "GRADUATE STUDIES",
    shelfCode: "GRADUATE STUDIES",
    categoryTitle: "Graduate Studies Collection",
    targetCollege: "Graduate School / Advanced Research",
    iconType: "Journal",
    generalCollectionSummary: "Koleksyon ng mga masteral at doctoral theses, research monographs, at specialized academic references para sa post-graduate studies.",
    studentGuidance: "Nasa unang malaking estante sa kanang bahagi ng Circulation and Reservation Room.",
    floor: "ground",
    zone: "circulation",
    position: { x: 74, y: 62 },
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "TEN YEARS RECENCY (1)",
    shelfCode: "10-YR RECENCY (B)",
    categoryTitle: "Ten Years Recency (Stack B)",
    targetCollege: "General Circulation / All Colleges",
    iconType: "Journal",
    generalCollectionSummary: "Koleksyon ng mga aklat na inilathala sa loob ng nakaraang sampung taon para sa updated instructional reference at curriculum-aligned study.",
    studentGuidance: "Nasa gitnang estante sa kanang bahagi ng Circulation and Reservation Room.",
    floor: "ground",
    zone: "circulation",
    position: { x: 74, y: 44 },
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "TEN YEARS RECENCY",
    shelfCode: "10-YR RECENCY (A)",
    categoryTitle: "Ten Years Recency (Stack A)",
    targetCollege: "General Circulation / All Colleges",
    iconType: "Journal",
    generalCollectionSummary: "Unang bahagi ng pinakabagong mga aklat (published within the last 10 years) para sa pananaliksik ng mga mag-aaral.",
    studentGuidance: "Nasa dulong estante sa itaas na kanang bahagi ng Circulation and Reservation Room.",
    floor: "ground",
    zone: "circulation",
    position: { x: 74, y: 26 },
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "OPAC TERMINAL ",
    shelfCode: "OPAC TERMINAL",
    categoryTitle: "Online Public Access Catalog (OPAC)",
    targetCollege: "All Students & Faculty",
    iconType: "Monitor",
    generalCollectionSummary: "Dedicated computer terminals para mag-search ng availability, author, call numbers, at shelf location ng mga aklat sa PSAU library.",
    studentGuidance: "Nakatayo malapit sa entrance partition at katabi ng circulation desk.",
    floor: "ground",
    zone: "circulation",
    position: { x: 42, y: 80 },
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "BAGGAGE",
    shelfCode: "BAGGAGE COUNTER",
    categoryTitle: "Baggage Drop-off Area",
    targetCollege: "All Students & Visitors",
    iconType: "Storage",
    generalCollectionSummary: "Lalagyan ng bag, backpacks, at personal na gamit ng mga estudyante bago pumasok sa reading at stack areas.",
    studentGuidance: "Nasa bungad ng kwarto sa tapat ng entrance doors.",
    floor: "ground",
    zone: "circulation",
    position: { x: 38, y: 92 },
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "COMPUTER ID SCANNER",
    shelfCode: "ID SCANNER",
    categoryTitle: "Computer ID Scanner Turnstile",
    targetCollege: "All Students & Faculty",
    iconType: "Monitor",
    generalCollectionSummary: "Electronic entrance turnstile para sa biometric at barcode scanning ng PSAU Student ID.",
    studentGuidance: "Nasa pangunahing bungad ng library entrance lobby.",
    floor: "ground",
    zone: "general",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Fiction 1",
    shelfCode: "FICTION 1",
    categoryTitle: "Fiction & Novels (Authors A–H)",
    targetCollege: "All Students & Leisure Readers",
    iconType: "Journal",
    generalCollectionSummary: "Koleksyon ng mga nobelang Ingles at Filipino, contemporary fiction, at literary prose mula A hanggang H.",
    studentGuidance: "Nasa hilagang pader ng General Circulation Hall.",
    floor: "ground",
    zone: "ddc_stacks",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Fiction 2",
    shelfCode: "FICTION 2",
    categoryTitle: "Fiction & Literature (Authors I–P)",
    targetCollege: "All Students & Leisure Readers",
    iconType: "Journal",
    generalCollectionSummary: "Pangalawang seksyon ng mga kathang-isip at international bestsellers mula I hanggang P.",
    studentGuidance: "Nasa gitnang hilagang pader ng General Circulation Hall.",
    floor: "ground",
    zone: "ddc_stacks",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Fiction 3",
    shelfCode: "FICTION 3",
    categoryTitle: "Classic Literature (Authors Q–Z)",
    targetCollege: "All Students & Leisure Readers",
    iconType: "Journal",
    generalCollectionSummary: "Mga klasikong panitikan, anthologies, at nobela mula Q hanggang Z.",
    studentGuidance: "Nasa dulong hilagang pader ng General Circulation Hall.",
    floor: "ground",
    zone: "ddc_stacks",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "Facility_BookReturn",
    shelfCode: "RETURN BOX",
    categoryTitle: "Circulation Book Return Drop Box",
    targetCollege: "All Borrowers",
    iconType: "Storage",
    generalCollectionSummary: "Drop box para sa pagsasauli ng hiniram na libro pagkatapos ng borrowing period o kung sarado ang counter.",
    studentGuidance: "Nasa bukana ng 2nd floor malapit sa hagdan at Filipiniana Section.",
    floor: "second",
    zone: "filipiniana",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 01 BS ENTREPRENURSHIP UT AND TR",
    shelfCode: "THESIS UNIT 01",
    categoryTitle: "BS Entrepreneurship (UT / TR)",
    targetCollege: "College of Business Studies",
    iconType: "Journal",
    generalCollectionSummary: "Undergraduate Theses at Terminal Reports para sa BS Entrepreneurship.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row A, Unit 01.",
    floor: "second",
    zone: "filipiniana",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 04 BS INFORMATION TECHNOLOGY UNDERGRADUATE THESIS (UT)  CAPSTONE PROJECT (CP)",
    shelfCode: "THESIS UNIT 04",
    categoryTitle: "BS Information Technology (CP / UT)",
    targetCollege: "College of Engineering and Computer Studies",
    iconType: "Journal",
    generalCollectionSummary: "Capstone Projects, Software Documentation, at Systems Engineering theses ng BSIT.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row A, Unit 04.",
    floor: "second",
    zone: "filipiniana",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 05 BSA ANIMAL SCIENCE UNDERGRADUATE THESIS (UT)  FARM PRACTICES (FP)",
    shelfCode: "THESIS UNIT 05",
    categoryTitle: "BSA Animal Science (UT / FP)",
    targetCollege: "College of Agriculture Systems & Technology",
    iconType: "Journal",
    generalCollectionSummary: "Farm Practices at Undergraduate Theses ng Animal Science majors.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row A, Unit 05.",
    floor: "second",
    zone: "filipiniana",
    lastUpdated: "2026-09-24T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 13 BS CROP SCIENCE UNDERGRADAUTE THESIS (UT) FARM PRACTICES (FP), BS AGRICULTURE UNDERGRADUATE THESIS (UT)",
    shelfCode: "THESIS UNIT 13",
    categoryTitle: "BS Crop Science & Agriculture (UT)",
    targetCollege: "College of Agriculture Systems & Technology",
    iconType: "Journal",
    generalCollectionSummary: "Crop breeding, soil management, agronomy, at agricultural research papers.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row B, Unit 13.",
    floor: "second",
    zone: "filipiniana",
    lastUpdated: "2026-09-24T00:00:00Z"
  }
];

export const INITIAL_CATALOG: DDCShelfCatalog = {
  version: "1.0",
  lastUpdated: "2026-09-24T00:00:00Z",
  shelves: INITIAL_DDC_SHELVES
};
