import { DDCShelf, DDCShelfCatalog } from "@/types/shelf";

export const INITIAL_DDC_SHELVES: DDCShelf[] = [
  // =========================================================================
  // GROUND FLOOR (18 Objects)
  // =========================================================================
  {
    shelfID: "00.01 - 320.99 to 321.00 - 424.99",
    shelfCode: "00.01 - 320.99 to 321.00 - 424.99",
    categoryTitle: "General Works, Philosophy, Religion & Social Sciences",
    targetCollege: "College of Arts and Sciences / General Education",
    iconType: "Journal",
    generalCollectionSummary: "Comprehensive stacks covering DDC Classes 000 (Computer Science, Information, Systems), 100 (Philosophy & Psychology), 200 (Religion & Mythology), 300 (Social Sciences, Law, Education), and 400 (Language & Linguistics).",
    studentGuidance: "Ground floor main aisle stacks. Check DDC range 000–424.",
    floor: "ground",
    zone: "ddc_stacks",
    position: { x: 12.4, y: 16.2 },
    subdivisions: [
      "[000 – GENERALITIES & INFORMATION]",
      "Bibliography",
      "Library & Information Sciences",
      "General Encyclopedic works",
      "General serials & their indexes",
      "General organizations & Museology",
      "News media, journalism, publishing",
      "General collections",
      "Manuscripts & rare books",
      "[100 – PHILOSOPHY & PSYCHOLOGY]",
      "Metaphysics",
      "Epistemology, causation, humankind",
      "Paranormal phenomena",
      "Specific Philosophical Schools",
      "Psychology",
      "Logic",
      "Ethics (Moral Philosophy)",
      "Ancient, medieval, Oriental philosophy",
      "Modern Western philosophy",
      "[200 – RELIGION & THEOLOGY]",
      "Natural theology",
      "Bible",
      "Christian theology",
      "Christian moral & devotional theology",
      "Christian orders & local church",
      "Christian social theology",
      "Christian church history",
      "Christian denominations & sects",
      "Other & comparative religions",
      "[300 – SOCIAL SCIENCES]",
      "Political science",
      "Economics",
      "Law",
      "Public administration",
      "Social services; associations",
      "Education",
      "Commerce, communications, transport",
      "Customs, etiquette, folklore",
      "[400 – LANGUAGE & LINGUISTICS]",
      "Linguistics",
      "English & Old English",
      "Germanic languages; German",
      "Romance languages; French",
      "Italian, Romanian, Rhaeto-Romantic",
      "Spanish & Portuguese languages",
      "Italic languages; Latin",
      "Hellenic languages; Classical Greek",
      "Other languages"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "425.00 - 550.00 to 550.01 - 612.00",
    shelfCode: "425.00 - 550.00 to 550.01 - 612.00",
    categoryTitle: "Languages, Pure Sciences & Early Applied Sciences",
    targetCollege: "College of Arts and Sciences / Engineering",
    iconType: "Star",
    generalCollectionSummary: "Covers grammar, linguistics (400s), pure sciences including mathematics, physics, chemistry, biology, earth sciences (500s), and human physiology / early medical sciences (600s).",
    studentGuidance: "Ground floor middle aisle. Call numbers 425 to 612.",
    floor: "ground",
    zone: "ddc_stacks",
    position: { x: 16.4, y: 16.2 },
    subdivisions: [
      "[400 – LANGUAGE & LINGUISTICS]",
      "425 English Grammar & Syntax",
      "428 Standard English Usage",
      "Linguistics & Comparative Grammar",
      "Historical & Descriptive Linguistics",
      "[500 – NATURAL SCIENCES & MATHEMATICS]",
      "510 Mathematics, Algebra & Geometry",
      "520 Astronomy & Allied Sciences",
      "530 Physics & Classical Mechanics",
      "540 Chemistry & Allied Sciences",
      "550 Earth Sciences & Geology",
      "570 Life Sciences & Biology",
      "580 Botanical Sciences & Plant Biology",
      "590 Zoological Sciences & Animal Biology",
      "[600 – TECHNOLOGY & APPLIED SCIENCES]",
      "610 Medical Sciences & Medicine",
      "611 Human Anatomy & Cytology",
      "612 Human Physiology & Biophysics"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "612.01 - 631.29 to 631.30 - 634.69",
    shelfCode: "612.01 - 631.29 to 631.30 - 634.69",
    categoryTitle: "Medical Sciences, Engineering & Crop Agriculture",
    targetCollege: "College of Agriculture Systems & Technology",
    iconType: "HolographicBookCrest",
    generalCollectionSummary: "Human anatomy, pharmacology, engineering operations, agricultural engineering, agronomy, soil chemistry, and field crop cultivation (DDC 612–634).",
    studentGuidance: "Ground floor agriculture stacks. Call numbers 612.01 to 634.69.",
    floor: "ground",
    zone: "ddc_stacks",
    position: { x: 20.5, y: 16.2 },
    subdivisions: [
      "[610 – MEDICAL SCIENCES & HEALTH]",
      "Human Physiology & Metabolic Systems",
      "Pharmacology, Therapeutics & Toxicology",
      "Public Health & Preventive Medicine",
      "Pathology & Disease Management",
      "[620 – ENGINEERING & APPLIED OPERATIONS]",
      "Engineering & Allied Operations",
      "Mechanical & Electrical Engineering",
      "Civil, Environmental & Agricultural Engineering",
      "Sanitary & Municipal Engineering",
      "[630 – AGRICULTURE & CROP PRODUCTION]",
      "Farming Systems & Agricultural Operations",
      "Agronomy, Soil Chemistry & Fertility",
      "Soil Conservation & Irrigation Systems",
      "Plant Pathology, Pests & Weed Management",
      "Field Crops, Cereals & Grain Production",
      "Industrial Crops & Legumes"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "634.70 - 636.29 to 636.30 - 658.09",
    shelfCode: "634.70 - 636.29 to 636.30 - 658.09",
    categoryTitle: "Horticulture, Animal Husbandry & Commercial Tech",
    targetCollege: "College of Veterinary Medicine & Agriculture",
    iconType: "HolographicBookCrest",
    generalCollectionSummary: "Fruit culture, forestry, animal husbandry, poultry science, veterinary medicine, home economics, and commercial operations (DDC 634–658).",
    studentGuidance: "Ground floor agriculture & animal science stacks. Call numbers 634.70 to 658.09.",
    floor: "ground",
    zone: "ddc_stacks",
    position: { x: 10.6, y: 53.9 },
    subdivisions: [
      "[630 – HORTICULTURE & ANIMAL HUSBANDRY]",
      "Orchards, Fruit Culture & Pomology",
      "Forestry & Agroforestry Systems",
      "Garden Crops, Horticulture & Vegetables",
      "Animal Husbandry & Livestock Production",
      "Poultry Science, Breeding & Nutrition",
      "Dairy Products & Milk Processing",
      "Fisheries, Aquaculture & Wildlife Conservation",
      "[640 – HOME ECONOMICS & MANAGEMENT]",
      "Home Economics & Family Living",
      "Food, Nutrition & Commercial Hospitality",
      "Sewing, Clothing & Personal Living",
      "[650 – MANAGEMENT & AUXILIARY SERVICES]",
      "Management & Auxiliary Services",
      "Business Communication & Records",
      "Accounting & Bookkeeping Methods"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "658.10 - 658.79",
    shelfCode: "658.10 - 658.79",
    categoryTitle: "Business Administration & Management",
    targetCollege: "College of Business Studies",
    iconType: "Journal",
    generalCollectionSummary: "Corporate organization, financial administration, executive management, personnel management, and business logistics (DDC 658).",
    studentGuidance: "Ground floor management aisle. Call numbers 658.10 to 658.79.",
    floor: "ground",
    zone: "ddc_stacks",
    position: { x: 10.6, y: 67.9 },
    subdivisions: [
      "[658 – CORPORATE ORGANIZATION & FINANCE]",
      "Corporate Organization & Business Formation",
      "Financial Administration & Capital Budgeting",
      "Managerial Accounting & Cost Control",
      "Risk Management & Business Insurance",
      "[658 – HUMAN RESOURCES & OPERATIONS]",
      "Human Resource Management & Labor Relations",
      "Executive Leadership & Strategic Management",
      "Production Management & Operations Research",
      "Supply Chain Management & Material Logistics",
      "Quality Control & Total Quality Management"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "658.10 - 699.99",
    shelfCode: "658.10 - 699.99",
    categoryTitle: "Applied Management, Chemical Tech & Manufacturing",
    targetCollege: "College of Business Studies & Engineering",
    iconType: "Journal",
    generalCollectionSummary: "Comprehensive management literature, marketing, chemical engineering, manufacturing processes, and building construction (DDC 658–699).",
    studentGuidance: "Ground floor south stacks. Call numbers 658.10 to 699.99.",
    floor: "ground",
    zone: "ddc_stacks",
    position: { x: 10.6, y: 48.4 },
    subdivisions: [
      "[650 – MANAGEMENT & AUXILIARY SERVICES]",
      "Enterprise & Strategic Management",
      "Marketing, Sales Promotion & Distribution",
      "Executive Decision Making",
      "[660 – CHEMICAL & RELATED TECHNOLOGIES]",
      "Chemical Engineering & Industrial Chemistry",
      "Food Biotechnology & Commercial Processing",
      "Biochemical Engineering & Fermentation",
      "Agricultural Chemicals & Fertilizers",
      "[670 – MANUFACTURING & FABRICATION]",
      "Manufacturing & Industrial Operations",
      "Metal Fabrication & Machine Technologies",
      "Manufacture for Specific Uses & Woodwork",
      "[690 – BUILDINGS & CONSTRUCTION]",
      "Building Construction & Structural Design",
      "Construction Materials & Concrete Technology",
      "HVAC, Plumbing & Electrical Installations"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "700.00 - 807.99",
    shelfCode: "700.00 - 807.99",
    categoryTitle: "The Arts, Recreation & World Literature Stacks",
    targetCollege: "College of Arts and Sciences / General Education",
    iconType: "Star",
    generalCollectionSummary: "Civic & landscape art, architecture, sculpture, painting, photography, music, sports, recreation, and literary criticism (DDC 700–807).",
    studentGuidance: "Ground floor west wall stacks. Call numbers 700 to 807.",
    floor: "ground",
    zone: "ddc_stacks",
    position: { x: 15.2, y: 70.4 },
    subdivisions: [
      "[700 – THE ARTS & RECREATION]",
      "Civic, Environmental & Landscape Art",
      "Architecture, Design & Preservation",
      "Plastic Arts, Sculpture & Ceramics",
      "Drawing, Decorative & Graphic Arts",
      "Painting & Fine Arts Collections",
      "Photography, Digital Imaging & Video",
      "Music, Composition & Performance",
      "Recreation, Sports & Athletic Training",
      "[800 – LITERATURE & RHETORIC]",
      "General Literature & Literary Theory",
      "Rhetoric, Criticism & Literary Analysis",
      "Comparative Literature Studies"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "808.00 - 808.819",
    shelfCode: "808.00 - 808.819",
    categoryTitle: "Rhetoric, Literary Composition & Poetry Anthologies",
    targetCollege: "College of Arts and Sciences",
    iconType: "Journal",
    generalCollectionSummary: "Rhetoric, speech communication, creative writing, literary collections, and poetry anthologies (DDC 808).",
    studentGuidance: "Ground floor west wall stacks. Call numbers 808.00 to 808.819.",
    floor: "ground",
    zone: "ddc_stacks",
    position: { x: 20.6, y: 70.4 },
    subdivisions: [
      "[800 – RHETORIC & COMPOSITION]",
      "Composition, Rhetoric & Style Guides",
      "Research Writing & Academic Paper Drafting",
      "Creative Writing, Fiction & Prose Techniques",
      "Speech Communication & Public Speaking",
      "Debate, Argumentation & Persuasion",
      "[808 – LITERARY ANTHOLOGIES & POETRY]",
      "World Poetry Anthologies & Classical Verse",
      "Poetic Forms, Meter & Lyric Criticism",
      "Modern & Contemporary Poetic Works",
      "Collections of Literary Speeches & Essays"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "808.82 - 939.99",
    shelfCode: "808.82 - 939.99",
    categoryTitle: "Drama, World Literature & Ancient World History",
    targetCollege: "College of Arts and Sciences / General Education",
    iconType: "Compass",
    generalCollectionSummary: "Dramatic literature, world literary anthologies, geography, travel, biographies, and ancient world history (DDC 808–939).",
    studentGuidance: "Ground floor southwest stacks. Call numbers 808.82 to 939.99.",
    floor: "ground",
    zone: "ddc_stacks",
    position: { x: 25.4, y: 70.4 },
    subdivisions: [
      "[800 – DRAMA & WORLD LITERATURE]",
      "Dramatic Literature & Theatrical Masterpieces",
      "English & Old English Literature",
      "Literatures of Romance & Germanic Languages",
      "Philippine & Austronesian Literatures",
      "Asian, African & Middle Eastern Literatures",
      "[900 – GEOGRAPHY & WORLD HISTORY]",
      "Geography, Travel & World Cartography",
      "Biography, Genealogy & Historical Insignia",
      "History of Ancient World to 499 AD",
      "Ancient Civilizations: Egypt, Greece & Rome",
      "General History of Europe, Asia & Africa"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "Fiction 1",
    shelfCode: "FICTION 1",
    categoryTitle: "Fiction & Novels (Authors A–H)",
    targetCollege: "All Students & Leisure Readers",
    iconType: "Journal",
    generalCollectionSummary: "Koleksyon ng mga nobelang Ingles at Filipino, contemporary fiction, at literary prose mula A hanggang H.",
    studentGuidance: "Nasa hilagang pader ng General Circulation Hall.",
    floor: "ground",
    zone: "circulation",
    position: { x: 6.0, y: 47.4 },
    subdivisions: [
      "[Koleksyon ng Nobela (Authors A–H)]",
      "Contemporary Philippine Novels (A–H)",
      "Young Adult Fiction & Global Bestsellers",
      "Literary Classics & Drama (A–H)",
      "Historical Fiction & Narrative Prose",
      "[Patakaran at Gabay sa Fiction]",
      "Maximum 2 Fiction Books bawat hiram",
      "1 linggo loan period na maaaring i-renew",
      "Open shelves para sa lahat ng PSAU students",
      "Ingatan ang mga pahina at cover ng aklat"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "Fiction 2",
    shelfCode: "FICTION 2",
    categoryTitle: "Fiction & Literature (Authors I–P)",
    targetCollege: "All Students & Leisure Readers",
    iconType: "Journal",
    generalCollectionSummary: "Pangalawang seksyon ng mga kathang-isip at international bestsellers mula I hanggang P.",
    studentGuidance: "Nasa gitnang hilagang pader ng General Circulation Hall.",
    floor: "ground",
    zone: "circulation",
    position: { x: 6.0, y: 56.4 },
    subdivisions: [
      "[Koleksyon ng Nobela (Authors I–P)]",
      "World Literature & Translated Works (I–P)",
      "Mystery, Thriller & Detective Fiction",
      "Science Fiction & Speculative Novels",
      "Filipino Contemporary Literature (I–P)",
      "[Patakaran at Gabay sa Fiction]",
      "Maximum 2 Fiction Books bawat hiram",
      "1 linggo loan period na maaaring i-renew",
      "Open shelves para sa lahat ng PSAU students",
      "Ingatan ang mga pahina at cover ng aklat"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "Fiction 3",
    shelfCode: "FICTION 3",
    categoryTitle: "Classic Literature (Authors Q–Z)",
    targetCollege: "All Students & Leisure Readers",
    iconType: "Journal",
    generalCollectionSummary: "Mga klasikong panitikan, anthologies, at nobela mula Q hanggang Z.",
    studentGuidance: "Nasa dulong hilagang pader ng General Circulation Hall.",
    floor: "ground",
    zone: "circulation",
    position: { x: 6.0, y: 66.8 },
    subdivisions: [
      "[Koleksyon ng Nobela (Authors Q–Z)]",
      "Classic Masterpieces & Anthologies (Q–Z)",
      "Modern Fantasy & Graphic Literature",
      "Short Story Collections & Anthologies",
      "World Literary Classics (Q–Z)",
      "[Patakaran at Gabay sa Fiction]",
      "Maximum 2 Fiction Books bawat hiram",
      "1 linggo loan period na maaaring i-renew",
      "Open shelves para sa lahat ng PSAU students",
      "Ingatan ang mga pahina at cover ng aklat"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "GRADUATE STUDIES",
    shelfCode: "GRADUATE STUDIES",
    categoryTitle: "Graduate Studies Collection",
    targetCollege: "Graduate School / Advanced Research",
    iconType: "Journal",
    generalCollectionSummary: "Koleksyon ng mga masteral at doctoral theses, research monographs, at specialized academic references para sa post-graduate studies.",
    studentGuidance: "Nasa unang malaking estante sa kanang bahagi ng Circulation and Reservation Room.",
    floor: "ground",
    zone: "circulation",
    position: { x: 25.8, y: 51.2 },
    subdivisions: [
      "[Graduate Studies Collection]",
      "Masteral & Doctoral Theses (MA, MS, PhD)",
      "Advanced Post-Graduate Research Monographs",
      "Specialized Research Methodologies & Statistics",
      "Curriculum Design & Educational Leadership Volumes",
      "[Patakaran sa Paggamit]",
      "Eksklusibo para sa Graduate School at Advanced Researchers",
      "Room Use Only & Restricted Circulation",
      "Kinakailangan ang faculty endorsement o Graduate ID",
      "Mahigpit na ipinagbabawal ang pag-duplicate nang walang pahintulot"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "TEN YEARS RECENCY A",
    shelfCode: "10-YR RECENCY (A)",
    categoryTitle: "Ten Years Recency (Stack A)",
    targetCollege: "General Circulation / All Colleges",
    iconType: "Journal",
    generalCollectionSummary: "Unang bahagi ng pinakabagong mga aklat (published within the last 10 years) para sa pananaliksik ng mga mag-aaral.",
    studentGuidance: "Nasa dulong estante sa itaas na kanang bahagi ng Circulation and Reservation Room.",
    floor: "ground",
    zone: "circulation",
    position: { x: 25.8, y: 60.6 },
    subdivisions: [
      "[10 Years Recency Collection (A)]",
      "Academic Textbooks published within the last 10 years",
      "CHED & AACCUP Accreditation Standard References",
      "Updated College Curriculum Syllabi Textbooks",
      "Recent Editions for Sciences & Engineering",
      "[Patakaran at Akreditasyon]",
      "Regular circulation loan privileges apply",
      "3 Professional books for 3 days loan period",
      "Priority access para sa mga kumukuha ng major subjects",
      "Standard renewal policy via circulation desk or online"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "TEN YEARS RECENCY B",
    shelfCode: "10-YR RECENCY (B)",
    categoryTitle: "Ten Years Recency (Stack B)",
    targetCollege: "General Circulation / All Colleges",
    iconType: "Journal",
    generalCollectionSummary: "Koleksyon ng mga aklat na inilathala sa loob ng nakaraang sampung taon para sa updated instructional reference at curriculum-aligned study.",
    studentGuidance: "Nasa gitnang estante sa kanang bahagi ng Circulation and Reservation Room.",
    floor: "ground",
    zone: "circulation",
    position: { x: 25.8, y: 55.8 },
    subdivisions: [
      "[10 Years Recency Collection (B)]",
      "Recent Technical & Professional Acquisitions",
      "Modern Veterinary, Agriculture & Forestry Volumes",
      "Professional Licensure Exam Review Textbooks",
      "Latest Applied Sciences & Technology Manuals",
      "[Patakaran at Akreditasyon]",
      "Regular circulation loan privileges apply",
      "3 Professional books for 3 days loan period",
      "Priority access para sa mga kumukuha ng major subjects",
      "Standard renewal policy via circulation desk or online"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "COMPUTER ID SCANNER",
    shelfCode: "ID SCANNER",
    categoryTitle: "Computer ID Scanner Turnstile",
    targetCollege: "All Students & Faculty",
    iconType: "Monitor",
    generalCollectionSummary: "Electronic entrance turnstile para sa biometric at barcode scanning ng PSAU Student ID alinsunod sa Library Entry Protocols.",
    studentGuidance: "Nasa pangunahing bungad ng library entrance lobby.",
    floor: "ground",
    zone: "facility",
    position: { x: 43.5, y: 76.8 },
    subdivisions: [
      "[Client Monitoring Log System]",
      "Barcode & RFID PSAU Student ID Reader",
      "Automated Daily Attendance & Foot Traffic Counter",
      "Real-time Patron Entry Verification",
      "College & Department Statistical Monitoring",
      "[Patakaran sa Pagpasok]",
      "I-tap o i-scan ang valid School ID bago pumasok",
      "Prescribed School Uniform, PE Uniform, o College Shirt ang required",
      "Bawal ang walang ID o gumamit ng ID ng ibang estudyante",
      "Mag-log out o mag-scan muli sa paglabas"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "BAGGAGE",
    shelfCode: "BAGGAGE COUNTER",
    categoryTitle: "Baggage Drop-off Counter",
    targetCollege: "All Students & Visitors",
    iconType: "Storage",
    generalCollectionSummary: "Lalagyan ng bag, backpacks, at personal na gamit ng mga estudyante bago pumasok sa reading at stack areas.",
    studentGuidance: "Nasa bungad ng kwarto sa tapat ng entrance doors.",
    floor: "ground",
    zone: "facility",
    position: { x: 39.1, y: 69.0 },
    subdivisions: [
      "[Baggage Counter & Depository]",
      "Designated Personal Belongings Cubbies",
      "Backpack & Large Bag Depository Shelves",
      "Baggage Number Tag Issuance System",
      "Secure Monitored Counter Area",
      "[Patakaran sa Baggage Counter]",
      "Iwan ang lahat ng bag bago pumasok sa reading area",
      "Dalhin ang mahahalagang gamit (wallet, gadgets, valid ID)",
      "Bawal mag-iwan ng pagkain at inumin",
      "Huwag mag-iwan ng personal na gamit magdamag"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "OPAC TERMINAL ",
    shelfCode: "OPAC TERMINAL",
    categoryTitle: "Online Public Access Catalog (OPAC)",
    targetCollege: "All Students & Faculty",
    iconType: "Monitor",
    generalCollectionSummary: "Dedicated computer terminals para mag-search ng availability, author, call numbers, at shelf location ng mga aklat sa PSAU library.",
    studentGuidance: "Nakatayo malapit sa entrance partition at katabi ng circulation desk.",
    floor: "ground",
    zone: "facility",
    position: { x: 28.8, y: 28.0 },
    subdivisions: [
      "[Online Public Access Catalog (OPAC)]",
      "Catalog Search by Title, Author, Keyword, or Subject",
      "Call Number & Shelf Location Identification",
      "Real-Time Book Circulation Status & Due Date Check",
      "Access to PSAU Integrated Library System (ILS)",
      "[Gabay sa Paggamit ng OPAC]",
      "Hakbang 1: I-type ang pamagat, may-akda, o paksa sa search bar",
      "Hakbang 2: Kopyahin ang kumpletong Call Number sa ibinigay na call slip",
      "Hakbang 3: Alamin ang lokasyon (C, FIL, REF, FIC, GS, TH)",
      "Hakbang 4: Tumungo sa kaukulang floor at hanapin ang estante"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },

  // =========================================================================
  // SECOND FLOOR (28 Objects: 1 Facility, 13 Filipiniana/Special, 13 Theses)
  // =========================================================================
  {
    shelfID: "Facility_BookReturn",
    shelfCode: "RETURN BOX",
    categoryTitle: "Circulation Book Return Station",
    targetCollege: "All Borrowers",
    iconType: "Storage",
    generalCollectionSummary: "Drop box para sa pagsasauli ng hiniram na libro pagkatapos ng borrowing period o kung sarado ang counter upang maiwasan ang multa.",
    studentGuidance: "Nasa bukana ng 2nd floor malapit sa hagdan at Filipiniana Section.",
    floor: "second",
    zone: "facility",
    position: { x: 21.0, y: 52.3 },
    subdivisions: [
      "[Book Return Station]",
      "Circulation Book Return Slot & Receiving Counter",
      "Automated Check-In via Integrated Library System",
      "Condition & Physical Integrity Inspection",
      "Overdue Verification & Clearance Desk",
      "[Patakaran sa Pagbabalik]",
      "Ibalik ang mga aklat sa o bago ang itinakdang due date",
      "₱5.00 bawat araw na multa sa bawat regular na aklat kapag overdue",
      "₱5.00 bawat oras + ₱50/araw para sa reserve books",
      "Magbayad ng kaukulang multa sa University Cashier kung overdue"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 01: FIL 001.3 — FIL 304.6",
    shelfCode: "FIL 001.3 — FIL 304.6",
    categoryTitle: "Filipiniana: Generalities to Social Groups",
    targetCollege: "All Students & Researchers",
    iconType: "Journal",
    generalCollectionSummary: "Philippine research, humanities, indigenous knowledge systems, Philippine psychology, and sociological studies.",
    studentGuidance: "Filipiniana Row 1, Unit 01. Stacks FIL 001.3 to FIL 304.6.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 21.0, y: 64.3 },
    subdivisions: [
      "[000 – FILIPINIANA GENERALITIES]",
      "Philippine Bibliographies & National Catalogues",
      "Library & Information Science in the Philippines",
      "General Philippine Serials & Research Indexes",
      "Philippine Manuscripts & Rare Historical Prints",
      "[100 – FILIPINO PHILOSOPHY & PSYCHOLOGY]",
      "Sikolohiyang Pilipino (Virgilio Enriquez)",
      "Filipino Ethics, Values & Moral Philosophy",
      "Indigenous Thought & Worldviews",
      "[200 – RELIGION IN THE PHILIPPINES]",
      "Philippine Church History & Evangelization",
      "Folk Christianity & Indigenous Spirituality",
      "Comparative Religions & Interfaith Dialogue in PH",
      "[300 – PHILIPPINE SOCIAL SCIENCES]",
      "Philippine Demography & Population Studies",
      "Social Systems, Family & Community Dynamics"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 02: FIL 305.3 — FIL 338.16",
    shelfCode: "FIL 305.3 — FIL 338.16",
    categoryTitle: "Filipiniana: Social Structure & Agrarian Economics",
    targetCollege: "College of Education & Social Sciences",
    iconType: "Journal",
    generalCollectionSummary: "Philippine gender studies, community development, political science, and agricultural economics in the Philippines.",
    studentGuidance: "Filipiniana Row 1, Unit 02. Stacks FIL 305.3 to FIL 338.16.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 21.0, y: 71.5 },
    subdivisions: [
      "[300 – PHILIPPINE SOCIAL STRUCTURES]",
      "Gender Studies & Roles in Philippine Society",
      "Indigenous Peoples & Cultural Communities",
      "Social Classes, Urban & Rural Sociology",
      "[320 – PHILIPPINE POLITICS & GOVERNMENT]",
      "Philippine Political Science & Institutions",
      "Local Government Code & Public Administration",
      "Elections, Civil Society & Political Parties",
      "[330 – PHILIPPINE ECONOMY & INDUSTRY]",
      "Philippine Agricultural Economics & Agribusiness",
      "Agrarian Reform & Comprehensive Agrarian Reform Program (CARP)",
      "Rural Development & Cooperative Enterprise"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 03: FIL 338.4 — FIL 371.10",
    shelfCode: "FIL 338.4 — FIL 371.10",
    categoryTitle: "Filipiniana: Philippine Industry & Education",
    targetCollege: "College of Education & Business Studies",
    iconType: "Journal",
    generalCollectionSummary: "Philippine economic industries, labor laws, public administration, and pedagogical systems in Philippine schools.",
    studentGuidance: "Filipiniana Row 1, Unit 03. Stacks FIL 338.4 to FIL 371.10.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 21.0, y: 78.0 },
    subdivisions: [
      "[330 – PHILIPPINE INDUSTRIES & COMMERCE]",
      "Philippine Manufacturing & Agro-Industries",
      "Internal Trade, Commerce & Cooperative Movements",
      "Energy Resources & National Utilities",
      "[340 – PHILIPPINE LAW & JURISPRUDENCE]",
      "1987 Philippine Constitution & Constitutional Law",
      "Civil Code, Revised Penal Code & Labor Laws",
      "Philippine Agricultural, Environmental & Land Laws",
      "Supreme Court Decisions & Annotated Statutes",
      "[370 – PHILIPPINE EDUCATION & PEDAGOGY]",
      "Philippine Educational System & Foundations",
      "Teacher Education, Pedagogy & Classroom Management"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 04: FIL 371.27 — FIL 428",
    shelfCode: "FIL 371.27 — FIL 428",
    categoryTitle: "Filipiniana: Educational Assessment & Tagalog Linguistics",
    targetCollege: "College of Education & Arts & Sciences",
    iconType: "Journal",
    generalCollectionSummary: "School administration, educational testing, Filipino language studies, grammar, and bilingual education.",
    studentGuidance: "Filipiniana Row 1, Unit 04. Stacks FIL 371.27 to FIL 428.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 21.0, y: 84.0 },
    subdivisions: [
      "[370 – PHILIPPINE HIGHER EDUCATION]",
      "Higher Education Administration & CHED Policies",
      "Educational Testing, Measurement & Evaluation",
      "Curriculum Development in Philippine Schools",
      "[390 – CUSTOMS & FILIPINO FOLKLORE]",
      "Philippine Customs, Etiquette & Traditions",
      "Filipino Folklore, Myths, Legends & Epics",
      "Kapampangan Cultural Traditions & Festivities",
      "[400 – FILIPINO & PHILIPPINE LANGUAGES]",
      "Balarila ng Wikang Pambansa at Ortograpiya",
      "Amanung Sisuan: Kapampangan Grammar & Lexicon",
      "Tagalog, Ilokano, Cebuano & Regional Dialects",
      "English Language Teaching in the Philippine Context"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 05: FIL 428 — FIL 574.07",
    shelfCode: "FIL 428 — FIL 574.07",
    categoryTitle: "Filipiniana: Philippine Languages & Local Flora/Fauna",
    targetCollege: "College of Arts & Sciences",
    iconType: "Star",
    generalCollectionSummary: "Philippine linguistics, mathematics education in the Philippines, and Philippine biodiversity and biological studies.",
    studentGuidance: "Filipiniana Row 2, Unit 05. Stacks FIL 428 to FIL 574.07.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 10.1, y: 82.9 },
    subdivisions: [
      "[400 – PHILIPPINE LINGUISTICS & USAGE]",
      "Bilingual Education & Sociolinguistics in the Philippines",
      "Philippine Lexicography & Dictionaries",
      "English & Filipino Stylistics & Grammar Usage",
      "[500 – NATURAL SCIENCES IN THE PHILIPPINES]",
      "General Mathematics & Statistics in Local Researches",
      "Philippine Geology, Volcanology & Seismology",
      "Philippine Weather, Climatology & Typhoon Tracking",
      "Philippine Flora & Fauna Surveys",
      "Philippine Biodiversity, Ecology & Wildlife"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 06: FIL 574.88 — FIL 630",
    shelfCode: "FIL 574.88 — FIL 630",
    categoryTitle: "Filipiniana: Philippine Biology & Tropical Agriculture",
    targetCollege: "College of Agriculture Systems & Technology",
    iconType: "HolographicBookCrest",
    generalCollectionSummary: "Tropical ecosystems, Philippine medicinal plants, public health in the Philippines, and baseline Philippine agriculture.",
    studentGuidance: "Filipiniana Row 2, Unit 06. Stacks FIL 574.88 to FIL 630.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 12.5, y: 82.8 },
    subdivisions: [
      "[570 – PHILIPPINE LIFE SCIENCES]",
      "Philippine Molecular Biology & Biochemistry",
      "Mount Arayat Biodiversity & Forest Ecology",
      "Candaba Swamp Wetland Ecology & Avian Biology",
      "Philippine Botanical Taxonomy & Medicinal Plants",
      "[610 – PHILIPPINE MEDICINE & HEALTH]",
      "Public Health Administration in the Philippines",
      "Philippine Herbal Medicine & Indigenous Healing (PITAHC)",
      "Epidemiology & Community Health Care",
      "[620 – PHILIPPINE ENGINEERING & INFRASTRUCTURE]",
      "Philippine Agricultural Engineering Projects",
      "Rural Electrification & Appropriate Technologies"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 07: FIL 630 — FIL 633.18",
    shelfCode: "FIL 630 — FIL 633.18",
    categoryTitle: "Filipiniana: Philippine Rice Farming & Crop Production",
    targetCollege: "College of Agriculture Systems & Technology",
    iconType: "HolographicBookCrest",
    generalCollectionSummary: "Philippine rice farming techniques (Palay), soil management, irrigation, and field crop production across Luzon.",
    studentGuidance: "Filipiniana Row 2, Unit 07. Stacks FIL 630 to FIL 633.18.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 15.1, y: 82.7 },
    subdivisions: [
      "[630 – PHILIPPINE AGRICULTURE & FARMING]",
      "Tropical Agriculture in Central Luzon",
      "Soil Science, Soil Fertility & Conservation in PH",
      "Irrigation Management & NIA River Systems",
      "Plant Pathology & Pest Management in PH",
      "[633 – PHILIPPINE FIELD CROPS & RICE]",
      "Rice Cultivation & PhilRice Research Compendiums",
      "Corn, Sorghum & Cereal Crop Production",
      "Sugarcane Agriculture & Sugar Industry in Pampanga",
      "Cassava, Sweet Potato & Root Crops"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 08: FIL 633.18 — FIL 693.3",
    shelfCode: "FIL 633.18 — FIL 693.3",
    categoryTitle: "Filipiniana: Livestock, Fisheries & Applied Philippine Tech",
    targetCollege: "College of Veterinary Medicine & Agriculture",
    iconType: "HolographicBookCrest",
    generalCollectionSummary: "Philippine animal husbandry, aquaculture, native dishes and culinary arts, and local construction methods.",
    studentGuidance: "Filipiniana Row 2, Unit 08. Stacks FIL 633.18 to FIL 693.3.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 17.4, y: 82.8 },
    subdivisions: [
      "[634 – PHILIPPINE HORTICULTURE & FORESTRY]",
      "Philippine Fruit Crops (Carabao Mango, Banana, Papaya)",
      "Vegetable Production & Urban Gardening in PH",
      "Bamboo Farming & Utilization (PSAU Bamboo Project)",
      "Philippine Reforestation & Agroforestry Practices",
      "[636 – PHILIPPINE ANIMAL SCIENCE & VETERINARY]",
      "Water Buffalo (Carabao) Production & PCC Studies",
      "Native Chicken, Duck & Poultry Farming in PH",
      "Swine & Goat Husbandry in Central Luzon",
      "[690 – PHILIPPINE BUILDING & CRAFTS]",
      "Philippine Architecture & Indigenous Building Materials",
      "Bamboo, Rattan & Native Wood Construction"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 09: FIL 641.33 — FIL 659.1",
    shelfCode: "FIL 641.33 — FIL 659.1",
    categoryTitle: "Filipiniana: Philippine Commerce, Accounting & Marketing",
    targetCollege: "College of Business Studies",
    iconType: "Journal",
    generalCollectionSummary: "Filipino entrepreneurship, accounting practices, business marketing, and small enterprise management.",
    studentGuidance: "Filipiniana Row 3, Unit 09. Stacks FIL 641.33 to FIL 659.1.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 10.1, y: 90.0 },
    subdivisions: [
      "[640 – FILIPINO FOOD & HOME ECONOMICS]",
      "Kulinaryang Kapampangan & Regional Cuisines",
      "Philippine Food Preservation, Processing & Meat Technology",
      "Hospitality & Restaurant Management in the Philippines",
      "Family Living, Home Economics & Nutrition in PH",
      "[650 – PHILIPPINE BUSINESS & MARKETING]",
      "Micro, Small & Medium Enterprises (MSMEs) in Central Luzon",
      "Philippine Marketing, Consumer Behavior & Advertising",
      "Business Logistics & Distribution in the Philippines"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 10: FIL 660.6 — FIL 808.84",
    shelfCode: "FIL 660.6 — FIL 808.84",
    categoryTitle: "Filipiniana: Philippine Arts & Literature Anthologies",
    targetCollege: "College of Arts & Sciences",
    iconType: "Star",
    generalCollectionSummary: "Philippine art history, music, film, folk traditions, and literary essays written in Filipino and English.",
    studentGuidance: "Filipiniana Row 3, Unit 10. Stacks FIL 660.6 to FIL 808.84.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 12.5, y: 90.0 },
    subdivisions: [
      "[660 – PHILIPPINE AGRO-INDUSTRIAL PROCESSING]",
      "Food Biotechnology & Fermentation in the Philippines",
      "Sugar, Alcohol & Biofuel Processing",
      "Philippine Wood & Paper Industries",
      "[700 – PHILIPPINE ARTS & CULTURE]",
      "Philippine Visual Arts, Painting & Sculpture",
      "Kapampangan Ecclesiastical & Sacred Art",
      "Traditional Philippine Music & Performing Arts",
      "[800 – FILIPINO ESSAYS & RHETORIC]",
      "Panitikang Pilipino: Sanaysay at Talumpati",
      "Rhetoric, Creative Non-Fiction & Feature Writing in PH"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 11: FIL 808.85 — FIL 899.9",
    shelfCode: "FIL 808.85 — FIL 899.9",
    categoryTitle: "Filipiniana: Tagalog & Kapampangan Literary Works",
    targetCollege: "College of Arts & Sciences",
    iconType: "Journal",
    generalCollectionSummary: "Kapampangan poetry, plays, epic narratives, contemporary Philippine novels, and regional folklore.",
    studentGuidance: "Filipiniana Row 3, Unit 11. Stacks FIL 808.85 to FIL 899.9.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 15.1, y: 90.0 },
    subdivisions: [
      "[800 – PHILIPPINE SPEECH & DRAMA]",
      "Talumpating Pilipino & Public Oratory",
      "Dulaang Filipino & Theatrical Plays",
      "Philippine Short Story Anthologies & Novels",
      "[899 – PANITIKANG KAPAMPANGAN AT REGIONAL]",
      "Amado Yuzon, Juan Crisostomo Soto (Crissotan) Works",
      "Kapampangan Poetry, Zarzuelas & Kuriru",
      "Tagalog Literary Classics (Florante at Laura, Urbana at Felisa)",
      "Ilokano, Bikolano, Bisaya & Regional Literatures"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 12: FIL 900 — FIL 920",
    shelfCode: "FIL 900 — FIL 920",
    categoryTitle: "Filipiniana: Philippine History & Provincial Biographies",
    targetCollege: "All Students & Historians",
    iconType: "Compass",
    generalCollectionSummary: "General Philippine history, pre-colonial chronicles, the Philippine Revolution, and national hero biographies.",
    studentGuidance: "Filipiniana Row 3, Unit 12. Stacks FIL 900 to FIL 920.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 17.4, y: 90.0 },
    subdivisions: [
      "[900 – PHILIPPINE GEOGRAPHY & ATLASES]",
      "Philippine Cartography, Provincial Profiles & Gazetteers",
      "Geography & Natural Hazards of Central Luzon",
      "Historical Geography of Pampanga & Mount Arayat",
      "[920 – BIOGRAPHIES OF FILIPINO HEROES]",
      "Lives of Philippine National Heroes & Patriots",
      "Biographies of Philippine Presidents & Statesmen",
      "Prominent Historical Leaders & Educators of Pampanga"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "RIZALIANA: FIL 920 — FIL 959",
    shelfCode: "RIZALIANA: FIL 920 — FIL 959",
    categoryTitle: "Rizaliana Collection & Local Heritage",
    targetCollege: "All PSAU Students (GE-Rizal)",
    iconType: "Compass",
    generalCollectionSummary: "Comprehensive scholarly collection on Dr. Jose Rizal's life, writings, novels (Noli Me Tangere, El Filibusterismo), and Magalang / Pampanga historical records.",
    studentGuidance: "Second floor Rizaliana special bay. Required reading for Rizal course.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 21.0, y: 90.0 },
    subdivisions: [
      "[Rizaliana Collection (Buhay at mga Akda)]",
      "Noli Me Tangere & El Filibusterismo (Original & Translations)",
      "Mi Ultimo Adios, Poems & Scholarly Essays",
      "Letters & Epistolary Collections (Rizal-Blumentritt)",
      "Historical & Literary Critiques on Jose Rizal",
      "[Kasaysayan ng Rebolusyong Pilipino]",
      "Propaganda Movement & La Solidaridad",
      "Katipunan, Andres Bonifacio & 1896 Revolution",
      "Republic of Biak-na-Bato & Malolos Republic",
      "Philippine-American War & Historical Documents"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SPECIAL SECTION: TEN YEARS RECENCY",
    shelfCode: "SPECIAL: 10-YR RECENCY",
    categoryTitle: "Second Floor 10-Years Recency Special Stacks",
    targetCollege: "All Academic Colleges",
    iconType: "Journal",
    generalCollectionSummary: "Recent acquisitions and reference textbooks in Filipiniana and agricultural disciplines published within the last decade.",
    studentGuidance: "Second floor dedicated recency shelf near the study carrels.",
    floor: "second",
    zone: "filipiniana",
    position: { x: 11.5, y: 41.1 },
    subdivisions: [
      "[Ten Years Recency (Filipiniana)]",
      "Recently Published Philippine Academic Books (Last 10 Years)",
      "CHED & AACCUP Accredited Local Course References",
      "Recent Philippine Laws, Statutes & Administrative Orders",
      "Updated Local Agriculture, Science & Education Textbooks",
      "[Patakaran sa Paggamit]",
      "Priority circulation para sa mga mag-aaral ng Filipiniana",
      "3 Professional books for 3 days loan period",
      "Maaaring basahin sa General Reading Area o ipa-photocopy",
      "Mag-log sa Filipiniana Section desk bago hiramin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },

  // THESIS SECTION (Shelving Units 01–13)
  {
    shelfID: "SHELVING UNIT 01 BS ENTREPRENURSHIP UT AND TR",
    shelfCode: "THESIS UNIT 01",
    categoryTitle: "BS Entrepreneurship (UT / TR)",
    targetCollege: "College of Business Studies",
    iconType: "Journal",
    generalCollectionSummary: "Undergraduate Theses at Terminal Reports para sa BS Entrepreneurship. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row A, Unit 01.",
    floor: "second",
    zone: "theses",
    position: { x: 19.3, y: 35.8 },
    subdivisions: [
      "[BS Entrepreneurship Manuscripts]",
      "Undergraduate Theses (UT) on Enterprise Feasibility",
      "Technical Reports (TR) on Business Incubation",
      "Market Opportunity Analysis & Business Models",
      "Agri-Enterprise Innovation & Startup Case Studies",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 02 BS BIOLOGY UNDERGRADUATE THESIS (UT) & BS FISHERIES UNDERGRADUATE THESIS (UT)",
    shelfCode: "THESIS UNIT 02",
    categoryTitle: "BS Biology & BS Fisheries (UT)",
    targetCollege: "College of Arts & Sciences / Agriculture",
    iconType: "Star",
    generalCollectionSummary: "Undergraduate Theses for BS Biology and BS Fisheries covering aquatic ecosystems, botanical biodiversity, and fish culture. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row A, Unit 02.",
    floor: "second",
    zone: "theses",
    position: { x: 23.7, y: 35.8 },
    subdivisions: [
      "[BS Biology & Fisheries Manuscripts]",
      "BS Biology Undergraduate Theses (UT) on Botany & Zoology",
      "Microbiology, Genetics & Local Biodiversity Theses",
      "BS Fisheries Undergraduate Theses (UT) on Aquaculture",
      "Freshwater Ecology, Fish Breeding & Water Quality Researches",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 03 BS AGRICULTURAL BUSINESS UNDERGRADUATE THESIS (UT)  SPECIAL PROBLEM (SP)",
    shelfCode: "THESIS UNIT 03",
    categoryTitle: "BS Agricultural Business (UT / SP)",
    targetCollege: "College of Business Studies",
    iconType: "Journal",
    generalCollectionSummary: "Undergraduate Theses and Special Problems in Agribusiness value chain analysis, agricultural marketing, and enterprise management. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row A, Unit 03.",
    floor: "second",
    zone: "theses",
    position: { x: 28.0, y: 35.8 },
    subdivisions: [
      "[BS Agricultural Business Manuscripts]",
      "Undergraduate Theses (UT) on Agribusiness Economics",
      "Special Problems (SP) on Agricultural Commodity Supply Chains",
      "Value Chain Analysis for Rice, Corn & Vegetable Crops",
      "Farm Financial Management & Agricultural Cooperative Researches",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 04 BS INFORMATION TECHNOLOGY UNDERGRADUATE THESIS (UT)  CAPSTONE PROJECT (CP)",
    shelfCode: "THESIS UNIT 04",
    categoryTitle: "BS Information Technology (UT / CP)",
    targetCollege: "College of Engineering & Computer Studies",
    iconType: "Monitor",
    generalCollectionSummary: "Capstone Projects, Software Documentation, and Systems Engineering theses submitted by BSIT graduates. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row A, Unit 04.",
    floor: "second",
    zone: "theses",
    position: { x: 16.5, y: 46.2 },
    subdivisions: [
      "[BS Information Technology Capstones & Manuscripts]",
      "BS Information Technology Capstone Projects (CP)",
      "Web & Mobile Application System Documentation",
      "Database Architecture, IoT & Embedded Systems",
      "AI, Machine Learning & Agriculture Support Systems",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 05 BSA ANIMAL SCIENCE UNDERGRADUATE THESIS (UT)  FARM PRACTICES (FP)",
    shelfCode: "THESIS UNIT 05",
    categoryTitle: "BSA Animal Science (UT / FP - Vol 1)",
    targetCollege: "College of Agriculture Systems & Technology",
    iconType: "HolographicBookCrest",
    generalCollectionSummary: "Undergraduate Theses and Farm Practices reports focusing on livestock management, swine production, and poultry science. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row A, Unit 05.",
    floor: "second",
    zone: "theses",
    position: { x: 21.3, y: 46.2 },
    subdivisions: [
      "[BSA Animal Science Theses & Farm Practices]",
      "BSA Animal Science Undergraduate Theses (UT)",
      "Farm Practices (FP) Reports on Swine Nutrition & Production",
      "Poultry Broiler & Layer Feeding Trials",
      "Ruminant Management & Pasture Development Researches",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 06 BSA ANIMAL SCIENCE UNDERGRADUATE THESIS (UT) FARM PRACTICES (FP)",
    shelfCode: "THESIS UNIT 06",
    categoryTitle: "BSA Animal Science (UT / FP - Vol 2)",
    targetCollege: "College of Agriculture Systems & Technology",
    iconType: "HolographicBookCrest",
    generalCollectionSummary: "Continuing volume of BSA Animal Science undergraduate research and field farm practices. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row A, Unit 06.",
    floor: "second",
    zone: "theses",
    position: { x: 25.0, y: 46.2 },
    subdivisions: [
      "[BSA Animal Science Farm Practices Reports]",
      "Farm Practices (FP) on Dairy Carabao & Cattle Production",
      "Forage Production, Silage & Animal Nutrition Studies",
      "Animal Breeding, Reproductive Technologies & Health",
      "Commercial Livestock Farm Management Documentation",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 07 BSA ANIMAL SCIENCE FARM PRACTICES (FP), BSA MATHEMATICS UNDERGRADUATE THESIS (UT), BSA AGROFORESTRY UNDERGRADUATE THESIS (UT) FIELD PRACTICUM (FP)",
    shelfCode: "THESIS UNIT 07",
    categoryTitle: "Animal Sci / Math / Agroforestry (UT / FP)",
    targetCollege: "CAST & CAS",
    iconType: "Journal",
    generalCollectionSummary: "Interdisciplinary manuscripts spanning Animal Science farm practices, Applied Mathematics theses, and Agroforestry field practicums. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row B, Unit 07.",
    floor: "second",
    zone: "theses",
    position: { x: 16.5, y: 53.0 },
    subdivisions: [
      "[Agroforestry, Math & Animal Science Practicums]",
      "BSA Agroforestry Undergraduate Theses (UT) & Field Practicum (FP)",
      "Upland Agroforestry Systems & Watershed Management",
      "BSA Mathematics Undergraduate Theses (UT) on Applied Models",
      "BSA Animal Science Farm Practicum Documentation",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 08 BS DEVELOPEMTN COMMUNICATION UNDERGRADAUTE THESIS (UT), BS FORESTRY UNDERGRADUATE THESIS (UT)",
    shelfCode: "THESIS UNIT 08",
    categoryTitle: "BS DevComm & BS Forestry (UT)",
    targetCollege: "College of Agriculture Systems & Technology",
    iconType: "Journal",
    generalCollectionSummary: "Undergraduate Theses on Development Communication, community extension, forest conservation, and watershed management. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row B, Unit 08.",
    floor: "second",
    zone: "theses",
    position: { x: 21.3, y: 53.0 },
    subdivisions: [
      "[Development Communication & Forestry Researches]",
      "BS Development Communication Undergraduate Theses (UT)",
      "Community Radio, Agricultural Extension & Multimedia Studies",
      "BS Forestry Undergraduate Theses (UT) on Silviculture",
      "Forest Resource Management & Dendrology in Mount Arayat",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 09 BS HOSPITALITY MANAGEMENT PRACTICUM REPORT (PR)",
    shelfCode: "THESIS UNIT 09",
    categoryTitle: "BS Hospitality Management (PR - Vol 1)",
    targetCollege: "College of Business Studies",
    iconType: "Journal",
    generalCollectionSummary: "Practicum and terminal industry training reports in hotel, restaurant, and resort operations submitted by BSHM seniors. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row B, Unit 09.",
    floor: "second",
    zone: "theses",
    position: { x: 25.0, y: 53.0 },
    subdivisions: [
      "[Hospitality Management Practicum Reports]",
      "BS Hospitality Management Practicum Reports (PR)",
      "Hotel & Resort Operations Practicum Documentation",
      "Food & Beverage Service Industry Practicums",
      "Culinary Arts & Event Management On-the-Job Reports",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 10 BS HOSPITALITY MANAGEMENT PRACTICUM REPORT (PR) UNDERGRADAUTE THESIS REASEARCH PAPER (PR)",
    shelfCode: "THESIS UNIT 10",
    categoryTitle: "BS Hospitality Management (PR / UT - Vol 2)",
    targetCollege: "College of Business Studies",
    iconType: "Journal",
    generalCollectionSummary: "Advanced undergraduate research papers and practicum reports on hospitality trends, tourism, and food service. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row B, Unit 10.",
    floor: "second",
    zone: "theses",
    position: { x: 29.8, y: 53.0 },
    subdivisions: [
      "[Hospitality Management Research Papers & Reports]",
      "Undergraduate Theses (UT) on Hospitality Marketing",
      "Eco-Tourism & Agri-Tourism Development Studies in Pampanga",
      "Customer Service Quality & Sanitation Standards Researches",
      "Advanced Practicum Research Papers (PR)",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 11 BAELS UNDERGRADAUTE THESIS (UT), BS GEODETIC ENGINEERING UNDERGRADUATE THESIS (UT)",
    shelfCode: "THESIS UNIT 11",
    categoryTitle: "BAELS & BS Geodetic Engineering (UT)",
    targetCollege: "CAS & College of Engineering",
    iconType: "Journal",
    generalCollectionSummary: "Undergraduate theses in English language linguistics, discourse analysis, geodetic surveying, GIS mapping, and cadastral systems. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row B, Unit 11.",
    floor: "second",
    zone: "theses",
    position: { x: 16.5, y: 59.5 },
    subdivisions: [
      "[BAELS & Geodetic Engineering Manuscripts]",
      "BA English Language Studies (BAELS) Undergraduate Theses (UT)",
      "Discourse Analysis, Sociolinguistics & Stylistics Theses",
      "BS Geodetic Engineering Undergraduate Theses (UT)",
      "GIS, Remote Sensing, Cadastral & Topographic Surveys",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 12 BSA ABE UNDERGRADAUTE THESIS (UT)",
    shelfCode: "THESIS UNIT 12",
    categoryTitle: "BS Agricultural & Biosystems Engineering (UT)",
    targetCollege: "College of Engineering",
    iconType: "Star",
    generalCollectionSummary: "Theses in agricultural mechanization, post-harvest engineering, renewable energy, and soil & water conservation engineering. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row B, Unit 12.",
    floor: "second",
    zone: "theses",
    position: { x: 21.3, y: 59.5 },
    subdivisions: [
      "[Agricultural & Biosystems Engineering (ABE) Theses]",
      "BSA Agricultural and Biosystems Engineering (ABE) Theses",
      "Farm Power, Machinery & Agricultural Mechanization",
      "Soil and Water Conservation & Irrigation Engineering",
      "Post-Harvest Processing & Agricultural Waste Management",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVING UNIT 13 BS CROP SCIENCE UNDERGRADAUTE THESIS (UT) FARM PRACTICES (FP), BS AGRICULTURE UNDERGRADUATE THESIS (UT)",
    shelfCode: "THESIS UNIT 13",
    categoryTitle: "BS Crop Science & BS Agriculture (UT / FP)",
    targetCollege: "College of Agriculture Systems & Technology",
    iconType: "HolographicBookCrest",
    generalCollectionSummary: "Crop breeding, soil management, agronomy, farm practices, and comprehensive agricultural research papers. Room Use Only.",
    studentGuidance: "Nasa Thesis Section, Second Floor. Row B, Unit 13.",
    floor: "second",
    zone: "theses",
    position: { x: 29.8, y: 46.2 },
    subdivisions: [
      "[Crop Science & Agriculture Farm Practices and Theses]",
      "BS Crop Science Undergraduate Theses (UT)",
      "Agronomic Trials, Crop Breeding & Tissue Culture Studies",
      "Farm Practices (FP) on Organic Farming & Crop Management",
      "BS Agriculture General Theses & Farming Innovations",
      "[Patakaran sa Paggamit ng Thesis]",
      "For Room Use Only - mahigpit na bawal ilabas ng Theses Section",
      "Iwan ang School ID sa Theses Section Desk bago magbasa",
      "Bawal kumuha ng litrato o mag-photocopy nang walang pahintulot",
      "Ibalik ang manuskrito sa tamang shelving unit matapos basahin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },

  // =========================================================================
  // THIRD FLOOR (8 Objects: 1 Admin Desk, 5 Reference Shelves, 1 Periodicals, 1 Reading Area)
  // =========================================================================
  {
    shelfID: "Facility_AdminInfoDesk",
    shelfCode: "ADMIN & INFO DESK",
    categoryTitle: "Administration & Information Desk (OLM)",
    targetCollege: "All Students, Faculty & Visitors",
    iconType: "Monitor",
    generalCollectionSummary: "Office of Library Services and Museum (OLM). Sentrong tanggapan para sa opisyal na konsultasyon, student clearance, reference guidance, at pamamahala ng aklatan sa pamumuno ni OIC Director Sharon G. Rulloda.",
    studentGuidance: "Third Floor main administrative foyer directly across the stairs.",
    floor: "third",
    zone: "facility",
    position: { x: 48.0, y: 35.0 },
    subdivisions: [
      "[Office of Library Services & Museum (OLM)]",
      "Office of the Director (Sharon G. Rulloda, MLIS, RL)",
      "Technical Processing & Cataloging Section",
      "Strategic Communications & Patron Records Desk",
      "Senior Museum Researcher Consultation Office",
      "[Mga Serbisyo at Konsultasyon]",
      "Pag-isyu ng Referral Letters para sa visiting researchers",
      "Pagpili at pag-endorso ng bagong aklat at online journals",
      "Library Orientation, OPAC training at information literacy guidance",
      "Thesis archival and institutional repository submission"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVE REF 1",
    shelfCode: "REF SHELF 1",
    categoryTitle: "General Reference: Dictionaries & Encyclopedias",
    targetCollege: "All Colleges & General Education",
    iconType: "Journal",
    generalCollectionSummary: "General encyclopedias, international multilingual dictionaries, biographical dictionaries, and language references. Room Use Only.",
    studentGuidance: "Third Floor Reference Section, Unit 1.",
    floor: "third",
    zone: "reference",
    position: { x: 18.0, y: 40.0 },
    subdivisions: [
      "[General Encyclopedias & Dictionaries]",
      "Encyclopaedia Britannica & Encyclopedia Americana",
      "Merriam-Webster International Unabridged Dictionaries",
      "Roget's International Thesaurus Collections",
      "Oxford English Reference Compendiums",
      "[Patakaran sa Reference Section]",
      "For Room Use Only - mahigpit na bawal iuwi o i-checkout sa gabi",
      "Maaaring basahin sa 3rd Floor study carrels o ipa-photocopy",
      "Iwan ang School ID sa Reference Desk bago kumuha ng aklat",
      "Ibalik ang aklat sa book cart matapos gamitin (huwag ibalik sa shelf)"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVE REF 2",
    shelfCode: "REF SHELF 2",
    categoryTitle: "Scientific & Technical Reference Handbooks",
    targetCollege: "College of Engineering & Pure Sciences",
    iconType: "Star",
    generalCollectionSummary: "Engineering handbooks, scientific tables, mathematical formulas, chemical reference data, and environmental encyclopedias. Room Use Only.",
    studentGuidance: "Third Floor Reference Section, Unit 2.",
    floor: "third",
    zone: "reference",
    position: { x: 22.0, y: 40.0 },
    subdivisions: [
      "[Science, Technology & Agricultural Handbooks]",
      "CRC Handbook of Chemistry and Physics",
      "Perry's Chemical Engineers' Handbook",
      "Agricultural Engineering & Agronomy Field Handbooks",
      "Tropical Plant Protection & Crop Production Compendiums",
      "[Patakaran sa Reference Section]",
      "For Room Use Only - mahigpit na bawal iuwi o i-checkout sa gabi",
      "Maaaring basahin sa 3rd Floor study carrels o ipa-photocopy",
      "Iwan ang School ID sa Reference Desk bago kumuha ng aklat",
      "Ibalik ang aklat sa book cart matapos gamitin (huwag ibalik sa shelf)"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVE REF 3",
    shelfCode: "REF SHELF 3",
    categoryTitle: "Agricultural & Biological Reference Manuals",
    targetCollege: "College of Agriculture & Veterinary Medicine",
    iconType: "HolographicBookCrest",
    generalCollectionSummary: "Comprehensive veterinary compendiums, agricultural encyclopedias, botanical guides, and plant disease handbooks. Room Use Only.",
    studentGuidance: "Third Floor Reference Section, Unit 3.",
    floor: "third",
    zone: "reference",
    position: { x: 26.0, y: 40.0 },
    subdivisions: [
      "[Medical, Veterinary & Biological Encyclopedias]",
      "The Merck Veterinary Manual & Clinical References",
      "Veterinary Pharmacology & Therapeutics Handbooks",
      "Gray's Anatomy & Human Physiology Reference Atlases",
      "Encyclopedia of Life Sciences & Biological Systems",
      "[Patakaran sa Reference Section]",
      "For Room Use Only - mahigpit na bawal iuwi o i-checkout sa gabi",
      "Maaaring basahin sa 3rd Floor study carrels o ipa-photocopy",
      "Iwan ang School ID sa Reference Desk bago kumuha ng aklat",
      "Ibalik ang aklat sa book cart matapos gamitin (huwag ibalik sa shelf)"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVE REF 4",
    shelfCode: "REF SHELF 4",
    categoryTitle: "Social Sciences, Law & Statistical Yearbooks",
    targetCollege: "College of Education & Social Sciences",
    iconType: "Compass",
    generalCollectionSummary: "Philippine statistical yearbooks, legal codes, educational directories, and international organization reports. Room Use Only.",
    studentGuidance: "Third Floor Reference Section, Unit 4.",
    floor: "third",
    zone: "reference",
    position: { x: 18.0, y: 55.0 },
    subdivisions: [
      "[Social Sciences, Education & Law Compendiums]",
      "International Encyclopedia of the Social & Behavioral Sciences",
      "Philippine Annotated Laws & Legal Compendiums",
      "Handbook of Research on Educational Pedagogy",
      "Public Administration & Economic Development Handbooks",
      "[Patakaran sa Reference Section]",
      "For Room Use Only - mahigpit na bawal iuwi o i-checkout sa gabi",
      "Maaaring basahin sa 3rd Floor study carrels o ipa-photocopy",
      "Iwan ang School ID sa Reference Desk bago kumuha ng aklat",
      "Ibalik ang aklat sa book cart matapos gamitin (huwag ibalik sa shelf)"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "SHELVE REF 5",
    shelfCode: "REF SHELF 5",
    categoryTitle: "Atlases, Gazetteers & Geographic Indices",
    targetCollege: "All Students & Researchers",
    iconType: "Compass",
    generalCollectionSummary: "World and Philippine cartographic atlases, topographical maps, geographical gazetteers, and chronological almanacs. Room Use Only.",
    studentGuidance: "Third Floor Reference Section, Unit 5.",
    floor: "third",
    zone: "reference",
    position: { x: 22.0, y: 55.0 },
    subdivisions: [
      "[Humanities, History & World Atlases]",
      "The Times Comprehensive Atlas of the World",
      "Historical Atlases & World Civilization Timelines",
      "International Who's Who & Global Biographical Dictionaries",
      "Encyclopedia of World Philosophy & Religions",
      "[Patakaran sa Reference Section]",
      "For Room Use Only - mahigpit na bawal iuwi o i-checkout sa gabi",
      "Maaaring basahin sa 3rd Floor study carrels o ipa-photocopy",
      "Iwan ang School ID sa Reference Desk bago kumuha ng aklat",
      "Ibalik ang aklat sa book cart matapos gamitin (huwag ibalik sa shelf)"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "Shelf_REF_ReferencePeriodicals",
    shelfCode: "PERIODICALS & SERIALS",
    categoryTitle: "Bound Periodicals & Academic Journals",
    targetCollege: "All Researchers & Graduate Students",
    iconType: "Journal",
    generalCollectionSummary: "Bound volumes of Philippine and international peer-reviewed journals, agricultural magazines, university research bulletins, and newspapers. Room Use Only.",
    studentGuidance: "Third Floor Periodicals Section east wall racks.",
    floor: "third",
    zone: "periodicals",
    position: { x: 28.0, y: 55.0 },
    subdivisions: [
      "[Periodicals & Serials Section]",
      "Philippine Journal of Science & Agricultural Research",
      "Academic Peer-Reviewed Research Journals",
      "National & Local Daily Newspapers (Inquirer, Star, Bulletin)",
      "Professional Magazines & Agricultural Extension Bulletins",
      "[Patakaran sa Periodicals]",
      "For Library Use Only - bawal ilabas ng 3rd Floor Periodicals Room",
      "Basahin sa designated periodical carrels at ibalik sa display rack",
      "Mag-iwan ng ID sa Periodicals Desk kung hihiramin para i-photocopy",
      "Bawal gupitin o punitin ang mga artikulo sa diyaryo o magasin"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  },
  {
    shelfID: "READING AREA",
    shelfCode: "QUIET STUDY AREA",
    categoryTitle: "Third Floor Quiet Study & Reading Zone",
    targetCollege: "All Students",
    iconType: "Journal",
    generalCollectionSummary: "Itinalagang tahimik na lugar para sa seryosong pag-aaral at pananaliksik. Panatilihing maayos ang mga upuan at mesa. Mahigpit na ipinagbabawal ang pag-iwan ng personal na gamit, pagkain, at maingay na usapan.",
    studentGuidance: "Third Floor open hall with individual study carrels.",
    floor: "third",
    zone: "facility",
    position: { x: 45.0, y: 65.0 },
    subdivisions: [
      "[Third Floor Quiet Study & Research Carrels]",
      "Individual High-Focus Academic Study Carrels",
      "Spacious Natural-Lit Reading Tables",
      "Panoramic View of Mount Arayat & Campus Boulevard",
      "Distraction-Free Environment for Thesis Writing & Review",
      "[Patakaran sa Katahimikan]",
      "Strict 'Silence is Golden' policy sa buong 3rd floor",
      "I-set sa Silent Mode o i-off ang lahat ng cellular phones",
      "Bawal ang group discussions o maiingay na meeting dito"
    ],
    lastUpdated: "2026-09-27T00:00:00Z"
  }
];

export const INITIAL_CATALOG: DDCShelfCatalog = {
  version: "2.0",
  lastUpdated: "2026-09-27T00:00:00Z",
  shelves: INITIAL_DDC_SHELVES
};
